name: setup-aseprite-cli-action
description: GitHub Action to build and install the Aseprite CLI.
branding:
  icon: terminal
  color: white
runs:
  using: composite
  steps:
  - id: prepare
    run: bash ./prepare.sh
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
  # - id: cache
  #   uses: actions/cache@v3
  #   with:
  #     path: aseprite/build/bin
  #     key: ${{ runner.os }}-aseprite
  - run: ./build.sh
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
  - run: ./install.sh
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
