name: setup-aseprite-cli-action
description: GitHub Action to build and install the Aseprite CLI.
branding:
  icon: terminal
  color: white
runs:
  using: composite
  steps:
  - id: prepare
    run: su -c 'bash ./prepare.sh' calvin
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
  - id: cache
    uses: actions/cache@v4
    with:
      path: ${{ GITHUB.ACTION_PATH }}/build/bin
      key: ${{ runner.os }}-aseprite
  - run: su -c 'bash ./build.sh' calvin
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
  - run: su -c 'bash ./install.sh' calvin
    shell: bash
    working-directory: ${{ GITHUB.ACTION_PATH }}
